### ISSUE TITLE
Why setting library name manually?

### ISSUE THREAD

**Issue by Simon-L** [sonoro1234/LuaJIT-SDL2#1]
https://github.com/sonoro1234/LuaJIT-SDL2/blob/dd0d65fe841b9fc0821a15c4ef9355170a29f5d8/CMakeLists.txt#L9

On linux, this causes to build libSDL2.so instead of libSDL2-2.0.so, then when building your excellent work at [sonoro1234/LuaJIT-ImGui](https://github.com/sonoro1234/LuaJIT-ImGui) it won't find it at runtime because the SDL2::SDL2 target library LuaJIT-ImGui links against is libSDL2-2.0.so, which is very likely to be available on many linux systems but I think it's good to distribute all this in a relocatable package without any system dependencies. I think that's how Windows handles it.

By the way, I've been working on making all the SDL2 + OpenGL3 + ImGui with LuaJIT cross platform, I got it right on macos as well. Look at the Github actions workflow files and artifacts:
Sorry for messing with the whitepaces here though https://github.com/sonoro1234/LuaJIT-ImGui/compare/docking_inter...Simon-L:LuaJIT-ImGui:docking_inter

This repo builds everything at once: https://github.com/Simon-L/imgui-luajit-setup/blob/main/.github/workflows/build.yml

Because I really like to have everything self-contained I've also setup CI with nightly release on every push for a ready-to-use LuaJIT environement, also cross-platform :) https://github.com/Simon-L/hererocks/releases/tag/Nightly

**Comment by sonoro1234** [comment]
Every LuaJIT to SDL2 binding found in github uses that so that they can load the module with `ffi.load"SDL2"` whatever is the OS used (win32, linux or apple). Another reason is that loading with ffi any other SDL2 module different from the provided one could cause a mismatch between ffi.cdef definitions and binary definitions.



> By the way, I've been working on making all the SDL2 + OpenGL3 + ImGui with LuaJIT cross platform, I got it right on macos as well.

That would be very interesting to have in LuaJIT-ImGui. Perhaps you could do a PR? It would be better without space modifications to make it easier to check.

My repository for building it all is https://github.com/sonoro1234/anima where `LUAJIT_WINDOW_ONLY` in cmake skips other submodules

**Comment by Simon-L** [comment]
Thanks for your help.
I did some more research. In my build process I do this in order:
- install libgl and LuaJIT-GL into luajit_bin
- go to SDL subdirectory of LuaJIT-SDL2, build and install system-wide in /usr/local
- build and install LuaJIT-SDL2 into luajit_bin
- build LuaJIT-ImGui into luajit_bin

I removed my fix for the .so name but it seems when installing SDL2 it still installs the other names:
```
-- Installing: /usr/local/lib/libSDL2-2.0.so.0.2800.5
-- Installing: /usr/local/lib/libSDL2-2.0.so.0
-- Installing: /usr/local/lib/libSDL2-2.0.so
...
 -- Installing: /usr/local/lib/libSDL2.so
```

In the CMakeLists.txt for LuaJIT-ImGui: https://github.com/sonoro1234/LuaJIT-ImGui/blob/docking_inter/CMakeLists.txt#L145
`set(IMGUI_SDL_LIBRARY SDL2::SDL2)` this line will end up at linking as "/usr/local/lib/libSDL2-2.0.so.0.2800.5". For some reason the forced name of "SDL2" (without suffix) isn't reflected in the linking. This path is systemwide and will not match with the libSDL2.so installed by LuaJIT-SDL2

Hope that makes sense! Can you explain/show how anima builds against the right SDL2, finding the headers and libs etc?

**Comment by Simon-L** [comment]
Currently on Linux this is what I see:
```
ldd libcimgui_sdl.so 
...
	libSDL2-2.0.so.0 => /lib/x86_64-linux-gnu/libSDL2-2.0.so.0 (0x00007fa0cee15000)
```
this somehow segfaults probably because of mismatches. That's expected. To fix it I have to do:
```
$ patchelf --remove-needed libSDL2-2.0.so.0 libcimgui_sdl.so
$ patchelf --add-needed libSDL2.so libcimgui_sdl.so
$ ldd libcimgui_sdl.so                   
	...
	libSDL2.so => /tmp/soskso/mfx-base-app-ubuntu/bin/./libSDL2.so (0x00007f97b2625000)
$ LD_LIBRARY_PATH=. ./lua ../app/main.lua
```

Edit: It only segfaults on one of my Debian computers, it works on the other but it's purely luck -- and SDL's API stability. That explains why I didn't catch this segfault issue in the first place

**Comment by sonoro1234** [comment]
Have you tried building anima? The fact that SDL is a submodule makes the build process to link cimgui_sdl with this SDL.

**Comment by Simon-L** [comment]
> Have you tried building anima? The fact that SDL is a submodule makes the build process to link cimgui_sdl with this SDL.

Thanks, I was in fact just trying that and it works, the reason is indeed cmake's `add_subdirectory` is used. I'll have to adapt my repo for that, it's a good thing in the end.

It appears that anima (which I knew was the project that needed all your SDL2 and ImGui repositories) and my usecase will have a lot in common.

**Comment by sonoro1234** [comment]
You can use the cmake flag `-DLUAJIT_WINDOW_ONLY` to skip alot of things perhaps not needed.
